### PR TITLE
add new 2bbcode_hubzilla implementation based on 2bbcode_phpbb

### PR DESCRIPTION
**Pull request by slobinger**

### CODE REVIEW

**Comment by lilydjwg** [comment]
The Table of Contents section of README is changed. Could you update it accordingly instead?

**Comment by slobinger** [comment]
Yes, sorry I was so happy to found a solution to write my blogs in markdown, that I ve missed some of this important points.

**Comment by slobinger** [comment]
It was the markdown-toc plugin for vs code that has destroyed the toc - I have not realized it.
@lilydjwg  Which tool do you use to generate your toc?

**Comment by lilydjwg** [comment]
I do not usually generate toc for markdown. The README in this repo was created by @tajmone.

**Comment by tajmone** [comment]
@slobinger

> Which tool do you use to generate your toc?

The tool I used at the time is no loger available, it was an NPM package which was removed in the meantime.

Currently, I use __MarkdownTOC__,a Sublime Text package for autogenerating TOCs:

https://github.com/naokazuterada/MarkdownTOC

Alternatively, a good CLI tool which is not dependent on any specific editor would be __DocToc__:

https://www.npmjs.com/package/doctoc

**Pull request merged**
